openapi: 3.0.2
info:
  title: ''
  version: ''
paths:
  /api/v1/:
    get:
      operationId: listProducts
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
          description: ''
      tags:
      - api
    post:
      operationId: createProduct
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Product'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
          description: ''
      tags:
      - api
  /api/v1/lessons/:
    get:
      operationId: listLessons
      description: ''
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lesson'
          description: ''
      tags:
      - api
    post:
      operationId: createLesson
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lesson'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Lesson'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Lesson'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lesson'
          description: ''
      tags:
      - api
  /api/v1/lessons/{id}/:
    get:
      operationId: retrieveLesson
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this lesson.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lesson'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyLesson
      description: ''
      parameters:
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this lesson.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
  /api/v1/product/{product_id}/:
    get:
      operationId: retrieveLesson
      description: ''
      parameters:
      - name: product_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lesson'
          description: ''
      tags:
      - api
  /api/v1/product/{product_id}/lessons/{id}/:
    get:
      operationId: retrieveLesson
      description: ''
      parameters:
      - name: product_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this lesson.
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lesson'
          description: ''
      tags:
      - api
    delete:
      operationId: destroyLesson
      description: ''
      parameters:
      - name: product_id
        in: path
        required: true
        description: ''
        schema:
          type: string
      - name: id
        in: path
        required: true
        description: A unique integer value identifying this lesson.
        schema:
          type: string
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
          maxLength: 200
        lesson_views_count:
          type: integer
        total_viewing_time:
          type: integer
        student_count:
          type: integer
        purchase_percentage:
          type: string
          format: decimal
          multipleOf: 0.01
          maximum: 1000
          minimum: -1000
        owner:
          type: integer
      required:
      - title
      - owner
    Lesson:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        lessonview_set:
          type: array
          items:
            type: object
            properties:
              viewing_time:
                type: integer
              is_completed:
                type: boolean
        name:
          type: string
          maxLength: 200
        video_url:
          type: string
          format: uri
          maxLength: 200
          pattern: "^(?:[a-z0-9.+-]*)://(?:[^\\s:@/]+(?::[^\\s:@/]*)?@)?(?:(?:0|25[0-5]|2[0-4][0-9]|1[0-9]?[0-9]?|[1-9][0-9]?)(?:\\\
            .(?:0|25[0-5]|2[0-4][0-9]|1[0-9]?[0-9]?|[1-9][0-9]?)){3}|\\[[0-9a-f:.]+\\\
            ]|([a-z\xA1-\uFFFF0-9](?:[a-z\xA1-\uFFFF0-9-]{0,61}[a-z\xA1-\uFFFF0-9])?(?:\\\
            .(?!-)[a-z\xA1-\uFFFF0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z\xA1-\uFFFF-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\\
            .?|localhost))(?::[0-9]{1,5})?(?:[/?#][^\\s]*)?\\z"
        duration_seconds:
          type: integer
        created:
          type: string
          format: date-time
          readOnly: true
        last_viewed:
          type: string
          format: date-time
          nullable: true
        subject:
          type: integer
      required:
      - name
      - video_url
      - duration_seconds
      - subject
