# Generated by Django 4.2 on 2023-09-20 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='last_viewed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последнего просмотра'),
        ),
        migrations.AlterField(
            model_name='lessonview',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Статус "Просмотрено"/"Не просмотрено"'),
        ),
        migrations.AlterField(
            model_name='lessonview',
            name='viewing_time',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность просмотра'),
        ),
    ]
