# Generated by Django 4.2 on 2023-09-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_last_viewed_alter_lessonview_is_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lesson_views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='product',
            name='student_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='total_viewing_time',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
